### ISSUE TITLE
Dependency issue with illuminate/console

### ISSUE THREAD

**Issue by tuupola** [rocketeers/rocketeer-slack#12]
This is more of an issue with `illuminate/console` but a heads up for you here. Commands below fail because `illuminate/console` has locked the dependency of `symfony/console` to minor version number `2.5.*`. I am pretty sure Symfony semantic versioning could be trusted and `illuminate/console` should use `~2.5` instead.
 
```
$ composer require symfony/console
$ composer require anahkiasen/rocketeer
```

Are any features of `illuminate/console` used or would vanilla `symfony/console` be enough?

**Comment by Anahkiasen** [comment]
It's actually Rocketeer itself that expects a Console instance from illuminate/console, this may change in 3.0 to rely directly on Symfony Console (to allow easier integration into other frameworks). The symfony constraint thing I've already opened an issue about it but yeah, apparently it's by design

**Comment by tuupola** [comment]
I accidentally opened this first to wrong repository. But yeah decoupling Rocketeer more from Laravel would be a good idea.

https://github.com/rocketeers/rocketeer/issues/441
